export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  FORGETPASSWORD_REQUEST: "FORGETPASSWORD_REQUEST",
  FORGETPASSWORD_SUCCESS: "FORGETPASSWORD_SUCCESS",
  FORGETPASSWORD_FAILURE: "FORGETPASSWORD_FAILURE",

  RESETPASSWORD_REQUEST: "RESETPASSWORD_REQUEST",
  RESETPASSWORD_SUCCESS: "RESETPASSWORD_SUCCESS",
  RESETPASSWORD_FAILURE: "RESTPASSWORD_FAILURE",

  UPDATE_USERDETAIL_REQUEST: "UPDATE_USERDETAIL_REQUEST",
  UPDATE_USERDETAIL_SUCCESS: "UPDATE_USERDETAIL_SUCCESS",
  UPDATE_USERDETAIL_FAILURE: "UPDATE_USERDETAIL_FAILURE",

  USERS_SHIPPING_ADDRESS_REQUEST: "USERS_SHIPPING_ADDRESS_REQUEST",
  USERS_SHIPPING_ADDRESS_SUCCESS: "USERS_SHIPPING_ADDRESS_SUCCESS",
  USERS_SHIPPING_ADDRESS_FAILURE: "USERS_SHIPPING_ADDRESS_FAILURE",

  USERS_ADDMETHOD_REQUEST: "USERS_ADDMETHOD_REQUEST",
  USERS_ADDMETHOD_SUCCESS: "USERS_ADDMETHOD_SUCCESS",
  USERS_ADDMETHOD_FAILIURE: "USERS_ADDMETHOD_FAILURE",

  USERS_PLACEORDER_REQUEST: "USERS_PLACEORDER_REQUEST",
  USERS_PLACEORDER_SUCCESS: "USERS_PLACEORDER_SUCCESS",
  USERS_PLACEORDER_FAILURE: "USERWS_PLACEORDER_FAILURE",

  USERS_ADDRESS_REQUEST: "USERS_ADDRESS_REQUEST",
  USERS_ADDRESS_FAILURE: "USERS_ADDRESS_FAILURE",
  USERS_ADDRESS_SUCCESS: "USERS_ADDRESS_SUCCESS",

  USERS_CHANGEPASSWORD_REQUEST: "USERS_CHANGEPASSWORD_REQUEST",
  USERS_CHANGEPASSWORD_SUCCESS: "USERS_CHANGEPASSWORD_SUCCESS",
  USERS_CHANGEPASSWORD_FAILURE: "USERS_CHANGEPASSWORD_FAILURE",

  CONTACTUS_REQUEST: "CONTACTUS_REQUEST",
  CONTACTUS_SUCCESS: "CONTACTUS_SUCCESS",
  CONTACTUS_FAILURE: "CONTACTUS_FAILURE",

  SENDINVITATIONREQUEST: " SENDINVITATIONREQUEST",
  SENDINVITATIONSUCCESS: " SENDINVITATIONSUCCESS",
  SENDINVITATIONFAILURE: " SENDINVITATIONFAILURE",

  GETINVITATIONREQUEST: "GETINVITATIONREQUEST",
  GETINVITATIONSUCCESS: "GETINVITATIONSUCCESS",
  GETINVITATIONFAILURE: "GETINVITATIONFAILURE",

  NEWSLETTERSUBSCRIBEREQUEST: "NEWSLETTERSUBSCRIBEREQUEST",
  NEWSLETTERSUBSCRIBESUCCESS: "NEWSLETTERSUBSCRIBESUCCESS",
  NEWSLETTERSUBSCRIBEFAILURE: "NEWSLETTERSUBSCRIBEFAILURE",

  NEWSLETTERUNSUBSCRIBEREQUEST: "NEWSLETTERUNSUBSCRIBEREQUEST",
  NEWSLETTERUNSUBSCRIBESUCCESS: "NEWSLETTERUNSUBSCRIBESUCCESS",
  NEWSLETTERUNSUBSCRIBEFAILURE: "NEWSLETTERUNSUBSCRIBEFAILURE",

  GETUSERDETAILREQUEST: "GETUSERDETAILREQUEST",
  GETUSERDETAILSUCCESS: "GETUSERDETAILSUCCESS",
  GETUSERDETAILFAILURE: "GETUSERDETAILFAILURE",

  DELTEMULTIADDRESSREQUEST: "DELTEMULTIADDRESSREQUEST",
  DELTEMULTIADDRESSSUCCESS: "DELTEMULTIADDRESSSUCCESS",
  DELTEMULTIADDRESSFALIURE: "DELTEMULTIADDRESSFAILURE",

  EDITMULTIADDRESSEREQUEST: "EDITMULTIADDRESSEREQUEST",
  EDITMULTIADDRESSESUCCESS: "EDITMULTIADDRESSESUCCESS",
  EDITMULTIADDRESSEFAILURE: "EDITMULTIADDRESSEFAILURE",

  REORDERREQUEST: "REORDERREQUEST",
  REORDERSUCCESS: "REORDERSUCCESS",
  REORDERFAILURE: "REORDERFAILURE",

  ADDBILLINGADDRESSREQUEST: "ADDBILLINGADDRESSREQUEST",
  ADDBILLINGADDRESSSUCCESS: "ADDBILLINGADDRESSSUCCESS",
  ADDBILLINGADDRESSFAILURE: "ADDBILLINGADDRESSFAILUER",

  GETMYORDERSREQUEST: "GETMYORDERSREQUEST",
  GETMYORDERSSUCCESS: "GETMYORDERSSUCCESS",
  GETMYORDERSFAILURE: "GETMYORDERSFAILURE",
};
